version: "1"

services:
  vote:
    build: 
      dockerfile: Dockerfile.build
      image: 1991412/dastan
    command: npm start
    volumes:
     - ./vote:/app
    #depends_on:
    #  - db
    cached: true
