services:
  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
      image: dastan
    command: npm start
    volumes:
     - ./vote:/app
    #depends_on:
    #  - db
    cached: true
