apiVersion: v1
kind: Service
metadata:
  name: deepspeech
  namespace: default
  labels:
    app: deepspeech
spec:
  selector:
    app: deepspeech
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepspeech-deployment
  namespace: default
  labels:
    app: deepspeech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepspeech
  template:
    metadata:
      labels:
        app: deepspeech
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: dastan-docker
        image: 1991412/dastan
        ports:
        - containerPort: 80
